### ISSUE TITLE
Can't remove documents

### ISSUE THREAD

**Issue by flexjoly** [mjdenham/and-bible#37]
Hello,

I am trying to remove some bible/books etc. But they remain in the list.

I deleted it with the file manager for now, but i guess that should not be needed ;)

Greetz, flexjoly

**Comment by mjdenham** [comment]
Hi,

Please see this [FAQ entry](https://github.com/mjdenham/and-bible/wiki/FAQ#can-i-delete-a-document-from-and-bible).

Cheers
Martin

**Comment by flexjoly** [comment]
I do select 'delete' although it is greyed-out.
It does not work. 
![screenshot_2015-08-15-21-37-09](https://cloud.githubusercontent.com/assets/8533733/9290493/42e8d17e-4396-11e5-8d15-e5948d930e59.png)

**Comment by mjdenham** [comment]
Documents currently being displayed cannot be deleted, and neither can documents that have only just been downloaded.

So first select another document to ensure it is not selected.

Martin

**Comment by flexjoly** [comment]
I think I understand....
In this screen, you cannot delete anything...
Maybe you can remove the delete option here, it is a bit confusing.

The FAQ says "display the documents list", so I thought the 'download documents' is that list... There is no other 'list' in the menu. Maybe a screenshot or a more specific explanation, which documents list is meant.

Thanks so far!
