### ISSUE TITLE
Can't install on nook simple touch.

### ISSUE THREAD

**Issue by tnelsond** [mjdenham/and-bible#45]
I couldn't find an official apk to download that wasn't in an app store, so I downloaded http://apkpure.com/and-bible/net.bible.android.activity

I tried to install it using ES File Explorer, but I got:

Parse Error
There is a problem parsing the package.
[    OK    ]

**Comment by ildar** [comment]
Be careful of using untrusted sources.
I recommend:
1. F-Droid builds:
https://f-droid.org/repository/browse/?fdid=net.bible.android.activity
2. Original author's Alpha releases:
https://drive.google.com/folderview?id=0B1yZK0LYUsB7VGttRENldzhzRnM&usp=sharing#grid

Generally if you don't like Google's Market, then you can use an
alternative. My choice is OpenSource FOSS https://f-droid.org/

**Comment by tnelsond** [comment]
Thanks.

Drat, I should have checked this first, but it turns out my device is crap and won't let me install anything anymore. :/
Sorry.

**Comment by mjdenham** [comment]
For future reference the best place to get apks is the folder containing official releases:
https://drive.google.com/drive/u/0/folders/0B1yZK0LYUsB7NTd1TmZyQnpHNVU

**Comment by ildar** [comment]
Martin, why don't you use "Releases" on github? You can upload apks right
there.

**Comment by mjdenham** [comment]
Great idea Ildar, I didn't know about that, have now started using Github Releases and you can see today's release and I will also add some older releases.
