### ISSUE TITLE
custom readingplan

### ISSUE THREAD

**Issue by menamara** [mjdenham/and-bible#48]
The instructions for creating a custom readingplan that can be found on
https://code.google.com/p/and-bible/wiki/ReadingPlan
didn't work for me.

I modified one of the [example](https://github.com/mjdenham/and-bible/blob/master/AndBible/assets/readingplan/y1ot1nt1_OTandNT.properties) plans and put it in the folder `jsword/readingplan` on my mobile's SD card, but it was not on the list in the app.
The modifications to the file were a different file name `y1ot1nt1_test.properties` and a change in the first line to `1=Gen.1-Gen.2, Ps.1-Ps.2`.

I'm using Android 5.0.2 on a Motorola Moto E (2nd Gen.).

**Comment by mjdenham** [comment]
Did you manage to get this working?  It may be that you just need to restart And Bible.

**Comment by menamara** [comment]
I just installed the latest version and tried it again, it worked right away, thank you!
