### ISSUE TITLE
Unable to download documents

### ISSUE THREAD

**Issue by taylor-r** [mjdenham/and-bible#51]
I can download one bible after it installs, but when I go to the download documents window it tells me an error has occurred.

**Comment by mjdenham** [comment]
A few users have reported this and we are working on a fix. Do you have a
Samsung device.

Martin

I can download one bible after it installs, but when I go to the download
documents window it tells me an error has occurred

—
Reply to this email directly or view it on GitHub
<https://github.com/mjdenham/and-bible/issues/51>.

**Comment by mjdenham** [comment]
I have just released version 2.3.2 that should fix your problem.  It will
take a few hours until it is available as an update from Play Store.

Martin

**Comment by taylor-r** [comment]
I do have Samsung (gs4). It works great now. Thank you for the fix.

**Comment by howdev** [comment]
cannot download document with version 2.6.0 on S3

**Comment by mjdenham** [comment]
There are currently no known problems with downloads.  However, occasionally there are internet comms problems.  Please try again.
