### ISSUE TITLE
Feature Request: Ribbons

### ISSUE THREAD

**Issue by steelwil** [mjdenham/and-bible#56]
Hi

It would be great to have a special type of bookmark that works just like a ribbon in a physical bible.
This will make moving back and forth between scriptures in church easier. The back button can kind of work but then there is no forward button.

They are special as bookmarks in that they are movable, so it should be easy to move say the red ribbon around, just as in a physical bible.

Tx

**Comment by mjdenham** [comment]
Long-press the back button to show a history list allowing navigation to a specific point in history that does not delete intervening history so it also allows forward navigation.

**Comment by steelwil** [comment]
I did not know about this feature, I will test it out and see if it can work for me.

Tx
