### ISSUE TITLE
The Ear

### ISSUE THREAD

**Issue by cmahte** [mjdenham/and-bible#57]
Hi Martin,

Recently I purchased my wife a replacement Android device and at the same time Olive tree offered me NIV for free, so I put Olive Tree with NIV onto her phone, so she would finally have it there. Very quickly she asked me to put back AndBible, so it will speak again. :-) (The offer wasn't related to the purchase, just coincidental.)

Lately, when I pull out my phone in meetings and church, The ear icon scares me. I'm fat fingered using a small screen, and the ear is right next to the 'next version', and I do like to cycle through the versions... Now I'm always afraid i'm going to initiate a speech. I've been repeatedly checking the volume is zero before I hit the next version (like 3 times during the same sermon.) Is it possible if the volume is zero to grey out the ear? Or possibly have a setting to grey it out?

**Comment by mjdenham** [comment]
Don't be scared by 'the ear'.  After you press 'the ear' it is replaced by audio controls that allow you to stop the voice immediately should you make a mistake.

Martin

**Comment by ildar** [comment]
BTW , @logos, you can disable TTS in Android settings.
