### ISSUE TITLE
add change log to fdroid

### ISSUE THREAD

**Issue by treakiandroid** [mjdenham/and-bible#63]
please add a link to a changelogpage to the fdroid repository. thanks

**Comment by mjdenham** [comment]
Unfortunately I have nothing to do with fdroid.  You should contact fdroid.

Martin

**Comment by ildar** [comment]
Indeed that was the wrong question.
Martin, do you have the changelog summary page somewhere?

**Comment by mjdenham** [comment]
Hi Ildar,

The most detailed change log summary is with each release here:
https://github.com/mjdenham/and-bible/releases

Martin
