### ISSUE TITLE
Could and-bible be made to run on the Desktop?

### ISSUE THREAD

**Issue by steckerhalter** [mjdenham/and-bible#65]
I think and-bible is really nice and better than existing Desktop Bible Apps. Since it is Java based I guess it would be possible to run it on any Java environment. Do you think that would be something to consider?

**Comment by notetiene** [comment]
Are there already available desktop bible apps from [Crosswire](https://crosswire.org/applications/)? And Bible is a front-end for the JSword library.

Android does use the Java language, but with all its own APIs, someone should rather run an Android emulator to run And Bible.

**Comment by cmahte** [comment]
I have AndBible running in a mac osx and a Linux environment several times over, using emulators. If you really like it you might try that route before trying to design a new wheel. 

However, I prefer and recommend BibleTime for any desktop.  

http://bibletime.info/

**Comment by steckerhalter** [comment]
Thanks, I was using Xiphos until now but found it lacking compared to and-bible. bibletime seems to be better but it is also not very modern. For example if you add multiple versions you can't even move them right or left. Since and-bible is bringing in innovative features I thought having this same code being the basis for desktop and mobile would be really nice.

It's just something to consider. I'm not too fit in Java but might learn and help. I have an idea like:

- write generic code that does something on top of JSword (which is probably often necessary?)
- Android and the desktop app extend the classes to do whatever they need to achieve that is platform specific

**Comment by steckerhalter** [comment]
For example with both Xiphos and Bibletime copying verses is annoying. With Bibletime it seems not even possible to copy a verse range. The method of selecting multiple verses that was introduced recently with and-bible is quite nice compared to that.

**Comment by notetiene** [comment]
@mattzab It's inaccurate to say AndBible would become a Chrome extension. You must download an extension that acts as an emulator. That can be guessed by the size of the extension (201MiB).
While much easier to setup, it's still an emulator.

**Comment by mattzab** [comment]
Hm, I was thinking it was a runtime environment rather than an emulator. At
any rate, thank you for the correction if I'm missing the mark on that one.
I like that it's not platform specific or dependent, only that you have
chrome and that extension.

Blessings!
Matt

**Comment by timbze** [comment]
May be possible in the future with https://www.jetbrains.com/lp/compose-mpp/

**Comment by tuomas2** [comment]
> May be possible in the future with https://www.jetbrains.com/lp/compose-mpp/

It's similar idea as making IOS app. Almost complete rewrite.
