### ISSUE TITLE
Cannot scroll text

### ISSUE THREAD

**Issue by sydneyjd** [mjdenham/and-bible#67]
Ok, so i haven't been able to get around to this very quickly...
I'm running a rather ancient version of android (2.3.6), and on every version since 2.5.1 i cannot scroll the text using the touchscreen. All the menus and the top bar work, i can change chapters/books in the Bible, etc, even scroll using phone tilt works if i enable it, i just cannot scroll text using my screen.

If you have any more questions, feel free to ask. I don't know what other info to provide. I have tried every version up to 2.8.1 which i belive is the latest version with the same results.

Thanks!

-Sydney

**Comment by mjdenham** [comment]
Hi Sydney,

Unfortunately Android 2.3 is very old and difficult to support.  Every new development takes a while to get running on 2.3 and I believe that And Bible works correctly on most 2.3 devices.  Support for 2.3 will probably be dropped soon.

If you have a version of And Bible that works on your phone then I would stick with that.

Sorry
Martin
