### ISSUE TITLE
Error on days 264-266 of y1ot1nt1_OTandNT reading plan

### ISSUE THREAD

**Issue by richgriswold** [mjdenham/and-bible#75]
The Old Testament selection for days 264 through 266 of the `y1ot1nt1_OTandNT` reading plan is blank.  If I tap the *Passage* button, And Bible crashes.  If I tap the *Speak* button, I get a pop-up message stating that "An error has occurred".  Comparing the `y1ot1nt1_OTandNT.properties` file to the other files  in the `and-bible/ReadingPlanCreator/out/` repo directory shows some discrepancies with the way "Song of Songs" is encoded:

- y1ot1nt1_OTandNT.properties: "Sng "
- y1ot1nt1_OTthenNT.properties: "Song of Songs "
- y1ot1nt1_chronological.properties: "Song "
- y1ot1nt2_mcheyne.properties: "Song "
- y2ot1ntps2.properties: "Song."

I don't have an Android development environment set up so I can build a custom APK, but it looks like And Bible may not be handling the the encoding of Song of Songs properly.

Here is a screen shot showing the blank passage:
![screenshot_2017-02-18-14-05-47 small](https://cloud.githubusercontent.com/assets/25892903/23113044/16f1e89a-f6ea-11e6-9b68-15eaa9ce2496.png)

After tapping *Speak*:
![screenshot_2017-02-18-14-06-16 small](https://cloud.githubusercontent.com/assets/25892903/23113043/16f163fc-f6ea-11e6-9d22-3c5453f41748.png)

After taping *Passage*:
![screenshot_2017-02-18-14-06-21 small](https://cloud.githubusercontent.com/assets/25892903/23113045/16f23462-f6ea-11e6-8771-05d405036ddb.png)

**Comment by mjdenham** [comment]
Fixed for next release.
