### ISSUE TITLE
niv version

### ISSUE THREAD

**Issue by CanadianJeff** [mjdenham/and-bible#87]
The youversion app has the NIV bible how do I get in this

**Comment by aharris88** [comment]
I was going to ask a similar question. I'm curious what API(s) this app uses. I'm interested in using NIV (2011) and CSB (new version of HCSB).

**Comment by mjdenham** [comment]
We would all love to have the NIV.  Unfortunately it is copyrighted and we do not have permission to distribute it.

Martin

**Comment by aharris88** [comment]
What API does this app use?

**Comment by ildar** [comment]
It is using Sword Bible format through JSword API, if you care.
