### ISSUE TITLE
Font issue with Greek NTs

### ISSUE THREAD

**Issue by gottesfurcht** [mjdenham/and-bible#92]
Hi

I have made a SWORD module from the Greek NT of the Church of Greece, which is similar to the Antoniades, but has accents: www.myriobiblos.gr/bible/nt2/

My module and the code is here: https://github.com/gottesfurcht/myrio

The module has a font issue in and-bible. I doesn't switch to the Greek font which is necessary to render the accents. I have tried various things, like specifying the font etc. but to no avail.

I found that other modules have the same issue, for example the two Greek modules from eBible.org: grcSBL2010eb and grcTischeb

Even though both have the same configuration (font etc.) SBLGNT switches to the right font and Tischendorf does not. MorphGNT is also not switching to the Greek font and the letters with accents are missing.

Any idea what is causing this and how to fix it? Thanks, Ruben

**Comment by mjdenham** [comment]
There is information about the font framework and how to manually specify fonts [here](https://github.com/mjdenham/and-bible/wiki/Font-Framework).  The default overrides are specified in [this file](http://crosswire.org/and-bible/fonts/v1/fonts.properties).  Do you like the Greek font used for SBLGNT?  I did not know why it looked so cursive but could not change it.  Do we need to override the font for more Greek modules?  Is there a better Greek font?

**Comment by gottesfurcht** [comment]
Thank you very much for this information. The TNT also works on my device btw (is it getting overriden?). It seems to use the same font like SBLGNT. I also noticed that the font is a bit cursive but otherwise it looks quite good to me. MorphGNT and Tischendorf (`grcTischeb`) should be overridden too. I think the "Old Standard" font is quite nice: https://web.archive.org/web/20130529174622/http://www.thessalonica.org.ru:80/en/fonts-download.html (the website is offline, hence archive.org, this font is available in most Linux distributions)

**Comment by mjdenham** [comment]
I was really looking for somebody to do all the required testing and give me a new font.properties file.

**Comment by gottesfurcht** [comment]
Allright :) I'll try to test some more and find the the right tweaks for `font.properties`...

**Comment by gottesfurcht** [comment]
Ok, so the download link is dead for the TTF "old-standard". It's available from Debian for example: http://ftp.us.debian.org/debian/pool/main/f/fonts-oldstandard/fonts-oldstandard_2.2really-3_all.deb

**Comment by gottesfurcht** [comment]
I tried with the `old-standard` font but honestly I think `SBL_grk.ttf` looks better and is easier to read on the small screen . I might try some other fonts later.

**Comment by gottesfurcht** [comment]
After a bit of searching I found a really nice font called `IFAOGrec` which is clean and easy to read: http://www.ifao.egnet.net/publications/publier/outils-ed/polices/#grec [Download Link](http://www.ifao.egnet.net/uploads/polices/IFAOGrec_2nd_edition.zip)

I think it would be more convenient to specify e.g. `grc=IFAOGrec.ttf` in the properties file and to preload the font when the user decides to download modules from the internet (as it is loading the indexes if that is possible).

**Comment by mjdenham** [comment]
Thanks for looking into this.  I need to think how best to roll this out.

Can I ask which version of Android you have been testing on?

**Comment by mjdenham** [comment]
I have done some experiments on my own device, comparing MorphGnt and Tisch, with and without the font you suggest and I can't see any missing accents, although obviously the font looks different.  Could you give me an example of accents that are missing - please bear in mind I know little about Greek.

**Comment by gottesfurcht** [comment]
The problem occurred on Android 4.4.2. Now I tried on another device with 5.1.1 and indeed there the accents are not missing 8o

It looks like older versions of Android probably use a font that doesn't contain the accents?

**Comment by mjdenham** [comment]
I think in that case I will leave things as they are.  I quite like the default Android Greek font.

**Comment by gottesfurcht** [comment]
Agreed. If I would have only tested on the other Android first :smile:  Thanks for looking into it...
