### ISSUE TITLE
Error getting bible text error when using custom module

### ISSUE THREAD

**Issue by janis-veinbergs** [mjdenham/and-bible#95]
I'v built a custom module and when loaded into And Bible (2.9.1) from ZIP, it shows the following error:
`Error getting bible text: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference.`

# Technical details

On Galaxy S6 Edge with Android 7.
However the previous device also failed with some similar error "Error getting bible text" which was Android 5 device.

Both modules work on Xiphos on Windows and in PocketSword on iOS.

Schema validation:
```
xmllint --noout --schema http://www.bibletechnologies.net/osisCore.2.1.1.xsd bihbele9.xml
bihbele9.xml validates
```

Text format:
```
ModDrv=zText
CompressType=ZIP
BlockType=Book
Encoding=UTF-8
```

Currently i'm preparing for module publishing and want to be sure it works on Android too.

# Could be related issue
It may be related, but it is possible to bring And Bible to **unusable state**. When I afterwards click on Bookmarks and then back, And Bible immediatelly crashes.

Third thing: I had also a custom module that was working years before but when I try to load it after this first module, And Bible crashes. And I cannot open it anymore if I don't clear app data. It immediately crashes when opened. This may be an separate issue that there is a code path that makes And Bible unusable.

I can send you the module somehow for testing.

**Comment by mjdenham** [comment]
Could you raise the issue in the [And Bible Discussion Group](https://groups.google.com/forum/#!forum/and-bible) as I don't have much experience in module creation.

**Comment by janis-veinbergs** [comment]
Thank you. Posted the question there.

**Comment by janis-veinbergs** [comment]
The issue appears to be because .conf file was encoded with UTF-8 BOM. BOM had to be removed and everything worked well.

It appears that C++ engine handles that case where JSword doesn't. However Crosswire [DevTools:conf Files](https://crosswire.org/wiki/DevTools:conf_Files) page states the point which I missed and didn't validate:

> Having a Byte Order Mark (BOM) at the beginning of the file[1]
> U+FEFF
> [KJV]

Relevant discussion on And Bible Discussion Group: [Error getting bible text error when using custom module. How to validate module?](https://groups.google.com/forum/#!topic/and-bible/BdE02k3nmC0)
